-- Seed 24 advisors from War Desk V6 prototype
-- Using uuid_generate_v5 with DNS namespace for deterministic UUIDs from original numeric IDs

insert into public.advisors (id, name, title, branch, category, stars, focus, clearance, rate, bio, image_url, years_service) values
  (uuid_generate_v5(uuid_ns_dns(), 'wardesk-advisor-2'), 'Joseph Martin', '37th Vice Chief of Staff, US Army', 'Army', 'Army', 4, ARRAY['Programming & Budgeting', 'Multi-domain Operations', 'Enterprise Talent'], 'TS/SCI', 1200, 'General Joseph M. Martin served as the 37th Vice Chief of Staff of the Army — the second-highest ranking officer in the United States Army.', 'https://res.cloudinary.com/dmj9mlo6o/image/upload/v1769200057/Joe-Martin_uok62s.png', 36),
  (uuid_generate_v5(uuid_ns_dns(), 'wardesk-advisor-3'), 'Gus Perna', 'Commanding General, Army Materiel Command', 'Army', 'Army', 4, ARRAY['Global Supply Chain', 'Material Readiness', 'Operation Warp Speed'], 'TS/SCI', 1100, 'General Gustave F. Perna commanded Army Materiel Command, overseeing a global logistics enterprise spanning 150 countries.', 'https://res.cloudinary.com/dmj9mlo6o/image/upload/v1769199851/Gus-Perna_phrgsx.jpg', 39),
  (uuid_generate_v5(uuid_ns_dns(), 'wardesk-advisor-4'), 'Frank Gorenc', 'Commander, US Air Forces in Europe & Africa', 'Air Force', 'Air Force', 4, ARRAY['NATO Operations', 'Theater Command', 'Coalition Warfare'], 'TS/SCI', 1100, 'General Frank Gorenc commanded US Air Forces in Europe, Air Forces Africa, and NATO Allied Air Command.', 'https://res.cloudinary.com/dmj9mlo6o/image/upload/v1769199848/Frank-Gorenc_kduwow.jpg', 35),
  (uuid_generate_v5(uuid_ns_dns(), 'wardesk-advisor-5'), 'James Foggo', 'Commander, US Naval Forces Europe & Africa', 'Navy', 'Navy', 4, ARRAY['Naval Strategy', 'Undersea Warfare', 'Allied Operations'], 'TS/SCI', 1200, 'Admiral James G. Foggo III commanded U.S. Naval Forces Europe, Naval Forces Africa, and Allied Joint Force Command Naples.', 'https://res.cloudinary.com/dmj9mlo6o/image/upload/v1769200056/Jamie-Foggo_prel3i.jpg', 37),
  (uuid_generate_v5(uuid_ns_dns(), 'wardesk-advisor-6'), 'Tony Thomas', 'Commander, US Special Operations Command', 'SOF', 'SOF', 4, ARRAY['Special Operations', 'Counter-terrorism', 'Irregular Warfare'], 'TS/SCI', 1400, 'General Tony Thomas commanded United States Special Operations Command, leading all special operations forces across the globe.', 'https://res.cloudinary.com/dmj9mlo6o/image/upload/v1769200069/Tony-Thomas_t9lx3s.png', 38),
  (uuid_generate_v5(uuid_ns_dns(), 'wardesk-advisor-7'), 'Scott Swift', 'Commander, US Pacific Fleet', 'Navy', 'Navy', 4, ARRAY['Indo-Pacific Strategy', 'Maritime Operations', 'Force Projection'], 'TS/SCI', 1200, 'Admiral Scott H. Swift commanded the United States Pacific Fleet — the world''s largest fleet command.', 'https://res.cloudinary.com/dmj9mlo6o/image/upload/v1769200064/Scott-Swift_rknn9u.jpg', 37),
  (uuid_generate_v5(uuid_ns_dns(), 'wardesk-advisor-54'), 'Sir Chris Deverell', 'Commander, Joint Forces Command (UK)', 'Allied', 'OSD', 4, ARRAY['Joint Operations', 'Coalition Warfare', 'UK-US Alliance'], 'TS/SCI', 1100, 'General Sir Chris Deverell KCB MBE commanded the United Kingdom''s Joint Forces Command.', 'https://res.cloudinary.com/dmj9mlo6o/image/upload/v1769200066/Sir_Chris_Deverell_rovjlj.jpg', 38),
  (uuid_generate_v5(uuid_ns_dns(), 'wardesk-advisor-8'), 'Melissa Dalton', 'Under Secretary of the Army', 'OSD', 'OSD', 0, ARRAY['Defense Policy', 'Force Posture', 'Alliance Strategy'], 'TS/SCI', 1000, 'The Honorable Melissa Dalton served as Under Secretary of the Army and as Assistant Secretary of Defense for Homeland Defense.', 'https://res.cloudinary.com/dmj9mlo6o/image/upload/v1769200060/Melissa-Dalton_qklws5.jpg', 22),
  (uuid_generate_v5(uuid_ns_dns(), 'wardesk-advisor-9'), 'Chris Lowman', 'Asst. Secretary of the Army (Sustainment)', 'OSD', 'OSD', 0, ARRAY['Sustainment & Logistics', 'Army Modernization', 'Acquisition'], 'TS/SCI', 900, 'The Honorable Chris Lowman served as the 16th Assistant Secretary of the Army for Sustainment.', 'https://res.cloudinary.com/dmj9mlo6o/image/upload/v1769199841/Chris_Lowman_ouzxtw.jpg', 28),
  (uuid_generate_v5(uuid_ns_dns(), 'wardesk-advisor-10'), 'Randolph Alles', 'Acting Deputy Secretary, DHS', 'OSD', 'OSD', 2, ARRAY['Border Security', 'Federal Law Enforcement', 'Homeland Defense'], 'TS/SCI', 900, 'Major General Randolph ''Tex'' Alles served as the 25th Director of the United States Secret Service.', 'https://res.cloudinary.com/dmj9mlo6o/image/upload/v1769200063/Randolph-Alles_mznrty.jpg', 35),
  (uuid_generate_v5(uuid_ns_dns(), 'wardesk-advisor-11'), 'Heino Klinck', 'Deputy Asst. Secretary of Defense (East Asia)', 'OSD', 'OSD', 0, ARRAY['Indo-Pacific Policy', 'Security Cooperation', 'East Asia'], 'TS/SCI', 850, 'The Honorable Heino Klinck served as the Deputy Assistant Secretary of Defense for East Asia.', 'https://res.cloudinary.com/dmj9mlo6o/image/upload/v1769199852/Heino-Klinck_nka864.png', 30),
  (uuid_generate_v5(uuid_ns_dns(), 'wardesk-advisor-12'), 'Katrina McFarland', 'Asst. Secretary of Defense (Acquisition)', 'OSD', 'OSD', 0, ARRAY['Acquisition Strategy', 'Defense Procurement', 'Contract Mgmt'], 'TS/SCI', 950, 'The Honorable Katrina McFarland served as Assistant Secretary of Defense for Acquisition.', 'https://res.cloudinary.com/dmj9mlo6o/image/upload/v1769200059/Katrina-Mcfarland_xf4gsm.jpg', 25),
  (uuid_generate_v5(uuid_ns_dns(), 'wardesk-advisor-13'), 'Dave Armour', 'Deputy Director, DARPA', 'OSD', 'OSD', 0, ARRAY['Advanced R&D', 'Technology Transition', 'Innovation Programs'], 'TS/SCI', 900, 'Dave Armour served as Deputy Director of DARPA.', 'https://res.cloudinary.com/dmj9mlo6o/image/upload/v1769199844/Dave-Armour_bteada.jpg', 26),
  (uuid_generate_v5(uuid_ns_dns(), 'wardesk-advisor-14'), 'Bob Girrier', 'Director, Navy Staff (OPNAV)', 'Navy', 'Navy', 3, ARRAY['Naval Operations', 'Force Structure', 'Maritime Strategy'], 'TS/SCI', 900, 'Vice Admiral Bob Girrier served as the Director of the Navy Staff.', 'https://res.cloudinary.com/dmj9mlo6o/image/upload/v1769199838/Bob_Girrier_iliekh.jpg', 34),
  (uuid_generate_v5(uuid_ns_dns(), 'wardesk-advisor-28'), 'Andy Busch', 'Director, Defense Logistics Agency', 'Air Force', 'Air Force', 3, ARRAY['Global Logistics', 'Supply Chain', 'Fuel & Energy'], 'TS/SCI', 900, 'Lieutenant General Andy Busch served as Director of the Defense Logistics Agency.', 'https://res.cloudinary.com/dmj9mlo6o/image/upload/v1769199838/Andy_Busch_wa9vhh.jpg', 33),
  (uuid_generate_v5(uuid_ns_dns(), 'wardesk-advisor-33'), 'Dan Karbler', 'Commander, Army Space & Missile Defense', 'Army', 'Army', 3, ARRAY['Missile Defense', 'Space Operations', 'Hypersonic Weapons'], 'TS/SCI', 900, 'Lieutenant General Dan Karbler commanded Army Space and Missile Defense Command.', 'https://res.cloudinary.com/dmj9mlo6o/image/upload/v1769199843/Dan-Karbler_hdx6ls.png', 34),
  (uuid_generate_v5(uuid_ns_dns(), 'wardesk-advisor-37'), 'Francis Wiercinski', 'Commanding General, US Army Pacific', 'Army', 'Army', 3, ARRAY['Indo-Pacific Operations', 'Theater Command', 'Alliance Building'], 'TS/SCI', 900, 'Lieutenant General Francis J. Wiercinski commanded U.S. Army Pacific.', 'https://res.cloudinary.com/dmj9mlo6o/image/upload/v1769199847/Francis_Wiercinski_anr8ez.jpg', 36),
  (uuid_generate_v5(uuid_ns_dns(), 'wardesk-advisor-44'), 'Nycki Brooks', 'Deputy Director, Defense Intelligence Agency', 'Intel', 'Intel', 0, ARRAY['Defense Intelligence', 'SIGINT', 'Threat Assessment'], 'TS/SCI', 900, 'Nycki Brooks served as Deputy Director of the Defense Intelligence Agency.', 'https://res.cloudinary.com/dmj9mlo6o/image/upload/v1769200062/Nycki-Brooks_wbofdy.png', 28),
  (uuid_generate_v5(uuid_ns_dns(), 'wardesk-advisor-29'), 'C. Shane Clark', 'Vice Commander, Space Operations Command', 'Space Force', 'Space Force', 2, ARRAY['Space Operations', 'Satellite Systems', 'Space Domain Awareness'], 'TS/SCI', 850, 'Major General C. Shane Clark served as Vice Commander of Space Operations Command.', 'https://res.cloudinary.com/dmj9mlo6o/image/upload/v1769199841/C.-Shane-Clark_gqpwlz.jpg', 26),
  (uuid_generate_v5(uuid_ns_dns(), 'wardesk-advisor-15'), 'Tommy Beals', 'Commander, Naval Special Warfare', 'Navy', 'Navy', 2, ARRAY['Special Warfare', 'Naval Operations', 'Force Development'], 'TS/SCI', 850, 'Rear Admiral Tommy Beals commanded Naval Special Warfare Command, overseeing all Navy SEAL operations.', 'https://res.cloudinary.com/dmj9mlo6o/image/upload/v1769200067/Tommy-Beals_dyqqj4.jpg', 32),
  (uuid_generate_v5(uuid_ns_dns(), 'wardesk-advisor-30'), 'Bill Hix', 'Director, Army Futures & Concepts Center', 'Army', 'Army', 2, ARRAY['Army Modernization', 'Future Concepts', 'Multi-domain Operations'], 'TS/SCI', 800, 'Major General Bill Hix served as Director of the Army Futures and Concepts Center.', 'https://res.cloudinary.com/dmj9mlo6o/image/upload/v1769199839/Bill-Hix_ak2z9x.png', 32),
  (uuid_generate_v5(uuid_ns_dns(), 'wardesk-advisor-65'), 'Bruce Lindsey', 'Deputy CG, Army Cyber Command', 'Cyber', 'Cyber', 2, ARRAY['Cyber Operations', 'Information Warfare', 'Network Security'], 'TS/SCI', 850, 'Major General Bruce Lindsey served as Deputy Commanding General of Army Cyber Command.', 'https://res.cloudinary.com/dmj9mlo6o/image/upload/v1769199840/Bruce-Lindsey_t4s3hb.png', 28),
  (uuid_generate_v5(uuid_ns_dns(), 'wardesk-advisor-45'), 'Joanne Isham', 'Deputy Director, NGA', 'Intel', 'Intel', 0, ARRAY['Geospatial Intelligence', 'Satellite Imagery', 'ISR'], 'TS/SCI', 900, 'Joanne Isham served as Deputy Director of the National Geospatial-Intelligence Agency.', 'https://res.cloudinary.com/dmj9mlo6o/image/upload/v1769200055/Joanne_Isham_dwulj7.jpg', 30),
  (uuid_generate_v5(uuid_ns_dns(), 'wardesk-advisor-57'), 'Jack Vogt', 'Deputy Asst. SecDef (Nuclear Matters)', 'OSD', 'OSD', 0, ARRAY['Nuclear Policy', 'Strategic Deterrence', 'Arms Control'], 'TS/SCI', 900, 'Jack Vogt served as Deputy Assistant Secretary of Defense for Nuclear Matters.', 'https://res.cloudinary.com/dmj9mlo6o/image/upload/v1769199854/Jack_Vogt_tylnkj.jpg', 24);

-- Seed default availability for all advisors (Mon-Fri 9am-5pm ET)
insert into public.availability (advisor_id, day_of_week, start_time, end_time, timezone)
select a.id, dow.d, '09:00'::time, '17:00'::time, 'America/New_York'
from public.advisors a
cross join (values (1),(2),(3),(4),(5)) as dow(d);
